name: run-pylint

on:
  pull_request:
    branches:
    - main

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  pylint:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=/home/runner/work/open-weather-map/API_Req_to_OpenWeatherMap" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r API_Req_to_OpenWeatherMap/requirements.txt
      - name: Analysing the code with pylint
        run: |
          (pylint $(git ls-files '*.py') --fail-under 8) >> pylint-output.txt
      - uses: mshick/add-pr-comment@v2
        with:
          message-path: pylint-output.txt
          preformatted: true
