on: ["push", "pull_request"]

name: pytest/Coveralls
permissions:
  contents: write
  checks: write
  pull-requests: write
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    environment: coverage-badge-update
    steps:

    - uses: actions/checkout@v1

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install coveralls
        
    - name: Set secret for coveralls
      run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=/home/runner/work/open-weather-map/API_Req_to_OpenWeatherMap" >> $GITHUB_ENV

    - name: Coveralls
      run: |
        coverage run -m pytest
        coveralls
